UPDATE mypetstore.account SET email = '', firstname = '1', lastname = '1', status = null, addr1 = '', addr2 = '', city = '', state = '', zip = '', country = '', phone = '' WHERE userid = '1';
UPDATE mypetstore.account SET email = '22', firstname = '2', lastname = '2', status = null, addr1 = '2', addr2 = '2', city = '2', state = '2', zip = '2', country = '2', phone = '2' WHERE userid = '2';
UPDATE mypetstore.account SET email = 'a', firstname = 'a', lastname = 'a', status = null, addr1 = 'a', addr2 = 'a', city = 'aa', state = 'a', zip = 'a', country = 'a', phone = 'a' WHERE userid = 'a';
UPDATE mypetstore.account SET email = 'acid@yourdomain.com', firstname = 'ABC', lastname = 'XYX', status = 'OK', addr1 = '901 San Antonio Road', addr2 = 'MS UCUP02-206', city = 'Palo Alto', state = 'CA', zip = '94303', country = 'USA', phone = '555-555-5555' WHERE userid = 'ACID';
UPDATE mypetstore.account SET email = 'b', firstname = 'b', lastname = 'b', status = null, addr1 = 'b', addr2 = 'b', city = 'b', state = 'b', zip = 'b', country = 'b', phone = 'b' WHERE userid = 'b';
UPDATE mypetstore.account SET email = 'd', firstname = 'd', lastname = 'd', status = null, addr1 = 'd', addr2 = 'd', city = 'd', state = 'd', zip = 'd', country = 'd', phone = 'd' WHERE userid = 'd';
UPDATE mypetstore.account SET email = 'dd_dolo@163.com', firstname = null, lastname = null, status = null, addr1 = null, addr2 = null, city = null, state = null, zip = null, country = null, phone = null WHERE userid = 'dddolo';
UPDATE mypetstore.account SET email = '', firstname = '', lastname = '', status = null, addr1 = '', addr2 = '', city = '', state = '', zip = '', country = '', phone = '' WHERE userid = 'dd_dolo@163.com';
UPDATE mypetstore.account SET email = 'yourname@yourdomain.com', firstname = 'ABC', lastname = 'XYX', status = null, addr1 = '901 San Antonio Road', addr2 = 'MS UCUP02-206', city = 'Palo Alto', state = 'CA', zip = '94303', country = 'USA', phone = '555-555-5555' WHERE userid = 'j2ee';
UPDATE mypetstore.account SET email = '', firstname = '', lastname = '', status = null, addr1 = '', addr2 = '', city = '', state = '', zip = '', country = '', phone = '' WHERE userid = 'je22';
UPDATE mypetstore.account SET email = 'q', firstname = 'q', lastname = 'q', status = null, addr1 = 'q', addr2 = 'q', city = 'q', state = 'q', zip = 'q', country = 'q', phone = 'q' WHERE userid = 'q';
UPDATE mypetstore.account SET email = 're', firstname = 're', lastname = 're', status = null, addr1 = 're', addr2 = 're', city = 're', state = 're', zip = 're', country = 're', phone = 're' WHERE userid = 're';
UPDATE mypetstore.account SET email = 'dd_dolo@163.com', firstname = null, lastname = null, status = null, addr1 = null, addr2 = null, city = null, state = null, zip = null, country = null, phone = null WHERE userid = 'try03';
UPDATE mypetstore.account SET email = 'dd_dolo@163.com', firstname = null, lastname = null, status = null, addr1 = null, addr2 = null, city = null, state = null, zip = null, country = null, phone = null WHERE userid = 'try04';
UPDATE mypetstore.account SET email = 'dd_dolo@163.com', firstname = null, lastname = null, status = null, addr1 = null, addr2 = null, city = null, state = null, zip = null, country = null, phone = null WHERE userid = 'try05';
UPDATE mypetstore.account SET email = 'dd_dolo@163.com', firstname = null, lastname = null, status = null, addr1 = null, addr2 = null, city = null, state = null, zip = null, country = null, phone = null WHERE userid = 'try06';
UPDATE mypetstore.account SET email = 'dd_dolo@163.com', firstname = null, lastname = null, status = null, addr1 = null, addr2 = null, city = null, state = null, zip = null, country = null, phone = null WHERE userid = 'try07';
UPDATE mypetstore.account SET email = 'dd_dolo@163.com', firstname = null, lastname = null, status = null, addr1 = null, addr2 = null, city = null, state = null, zip = null, country = null, phone = null WHERE userid = 'try08';
UPDATE mypetstore.account SET email = 'dd_dolo@163.com', firstname = null, lastname = null, status = null, addr1 = null, addr2 = null, city = null, state = null, zip = null, country = null, phone = null WHERE userid = 'try09';
UPDATE mypetstore.bannerdata SET bannername = '<image src="../images/banner_birds.gif">' WHERE favcategory = 'BIRDS';
UPDATE mypetstore.bannerdata SET bannername = '<image src="../images/banner_cats.gif">' WHERE favcategory = 'CATS';
UPDATE mypetstore.bannerdata SET bannername = '<image src="../images/banner_dogs.gif">' WHERE favcategory = 'DOGS';
UPDATE mypetstore.bannerdata SET bannername = '<image src="../images/banner_fish.gif">' WHERE favcategory = 'FISH';
UPDATE mypetstore.bannerdata SET bannername = '<image src="../images/banner_reptiles.gif">' WHERE favcategory = 'REPTILES';
UPDATE mypetstore.category SET name = 'Birds', descn = '<image src="../images/birds_icon.gif"><font size="5" color="blue"> Birds</font>' WHERE catid = 'BIRDS';
UPDATE mypetstore.category SET name = 'Cats', descn = '<image src="../images/cats_icon.gif"><font size="5" color="blue"> Cats</font>' WHERE catid = 'CATS';
UPDATE mypetstore.category SET name = 'Dogs', descn = '<image src="../images/dogs_icon.gif"><font size="5" color="blue"> Dogs</font>' WHERE catid = 'DOGS';
UPDATE mypetstore.category SET name = 'Fish', descn = '<image src="../images/fish_icon.gif"><font size="5" color="blue"> Fish</font>' WHERE catid = 'FISH';
UPDATE mypetstore.category SET name = 'Reptiles', descn = '<image src="../images/reptiles_icon.gif"><font size="5" color="blue"> Reptiles</font>' WHERE catid = 'REPTILES';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-1';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-10';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-11';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-12';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-13';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-14';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-15';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-16';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-17';
UPDATE mypetstore.inventory SET qty = 9999 WHERE itemid = 'EST-18';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-19';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-2';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-20';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-21';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-22';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-23';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-24';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-25';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-26';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-27';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-28';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-3';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-4';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-5';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-6';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-7';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-8';
UPDATE mypetstore.inventory SET qty = 10000 WHERE itemid = 'EST-9';
UPDATE mypetstore.item SET productid = 'FI-SW-01', listprice = 16.50, unitcost = 10.00, supplier = 1, status = 'P', attr1 = 'Large', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-1';
UPDATE mypetstore.item SET productid = 'K9-DL-01', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Spotted Adult Female', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-10';
UPDATE mypetstore.item SET productid = 'RP-SN-01', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Venomless', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-11';
UPDATE mypetstore.item SET productid = 'RP-SN-01', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Rattleless', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-12';
UPDATE mypetstore.item SET productid = 'RP-LI-02', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Green Adult', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-13';
UPDATE mypetstore.item SET productid = 'FL-DSH-01', listprice = 58.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Tailless', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-14';
UPDATE mypetstore.item SET productid = 'FL-DSH-01', listprice = 23.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'With tail', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-15';
UPDATE mypetstore.item SET productid = 'FL-DLH-02', listprice = 93.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Adult Female', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-16';
UPDATE mypetstore.item SET productid = 'FL-DLH-02', listprice = 93.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Adult Male', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-17';
UPDATE mypetstore.item SET productid = 'AV-CB-01', listprice = 193.50, unitcost = 92.00, supplier = 1, status = 'P', attr1 = 'Adult Male', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-18';
UPDATE mypetstore.item SET productid = 'AV-SB-02', listprice = 15.50, unitcost = 2.00, supplier = 1, status = 'P', attr1 = 'Adult Male', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-19';
UPDATE mypetstore.item SET productid = 'FI-SW-01', listprice = 16.50, unitcost = 10.00, supplier = 1, status = 'P', attr1 = 'Small', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-2';
UPDATE mypetstore.item SET productid = 'FI-FW-02', listprice = 5.50, unitcost = 2.00, supplier = 1, status = 'P', attr1 = 'Adult Male', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-20';
UPDATE mypetstore.item SET productid = 'FI-FW-02', listprice = 5.29, unitcost = 1.00, supplier = 1, status = 'P', attr1 = 'Adult Female', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-21';
UPDATE mypetstore.item SET productid = 'K9-RT-02', listprice = 135.50, unitcost = 100.00, supplier = 1, status = 'P', attr1 = 'Adult Male', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-22';
UPDATE mypetstore.item SET productid = 'K9-RT-02', listprice = 145.49, unitcost = 100.00, supplier = 1, status = 'P', attr1 = 'Adult Female', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-23';
UPDATE mypetstore.item SET productid = 'K9-RT-02', listprice = 255.50, unitcost = 92.00, supplier = 1, status = 'P', attr1 = 'Adult Male', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-24';
UPDATE mypetstore.item SET productid = 'K9-RT-02', listprice = 325.29, unitcost = 90.00, supplier = 1, status = 'P', attr1 = 'Adult Female', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-25';
UPDATE mypetstore.item SET productid = 'K9-CW-01', listprice = 125.50, unitcost = 92.00, supplier = 1, status = 'P', attr1 = 'Adult Male', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-26';
UPDATE mypetstore.item SET productid = 'K9-CW-01', listprice = 155.29, unitcost = 90.00, supplier = 1, status = 'P', attr1 = 'Adult Female', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-27';
UPDATE mypetstore.item SET productid = 'K9-RT-01', listprice = 155.29, unitcost = 90.00, supplier = 1, status = 'P', attr1 = 'Adult Female', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-28';
UPDATE mypetstore.item SET productid = 'FI-SW-02', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Toothless', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-3';
UPDATE mypetstore.item SET productid = 'FI-FW-01', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Spotted', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-4';
UPDATE mypetstore.item SET productid = 'FI-FW-01', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Spotless', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-5';
UPDATE mypetstore.item SET productid = 'K9-BD-01', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Male Adult', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-6';
UPDATE mypetstore.item SET productid = 'K9-BD-01', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Female Puppy', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-7';
UPDATE mypetstore.item SET productid = 'K9-PO-02', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Male Puppy', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-8';
UPDATE mypetstore.item SET productid = 'K9-DL-01', listprice = 18.50, unitcost = 12.00, supplier = 1, status = 'P', attr1 = 'Spotless Male Puppy', attr2 = null, attr3 = null, attr4 = null, attr5 = null WHERE itemid = 'EST-9';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-21 00:16:36     http://localhost:8080/mypetstore/updateCartQuantities?null 更新购物车商品数量';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-21 00:18:53     http://localhost:8080/mypetstore/viewCategory?categoryId=FISH 跳转到商品种类 FISH';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-21 00:18:54     http://localhost:8080/mypetstore/viewProduct?productId=FI-FW-02 查看产品 Goldfish';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-21 00:18:56     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-20 (EST-20-null)数量+1 ';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-21 00:18:59     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-21 添加物品 (EST-21-null) 到购物车';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-21 00:19:02     http://localhost:8080/mypetstore/main?null 跳转到主界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-21 00:19:06     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-20 (EST-20-null)数量+1 ';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-21 00:19:16     http://localhost:8080/mypetstore/viewCategory?categoryId=FISH 跳转到商品种类 FISH';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 10:09:09     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 10:13:39     http://localhost:8080/mypetstore/viewCategory?categoryId=FISH 跳转到商品种类 FISH';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 10:13:42     http://localhost:8080/mypetstore/viewProduct?productId=FI-FW-01 查看产品 Koi';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 10:13:44     http://localhost:8080/mypetstore/viewItem?itemId=EST-4 查看具体商品 (EST-4-null)';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 10:13:52     http://localhost:8080/mypetstore/viewProduct?productId=FI-FW-01 查看产品 Koi';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 10:48:56     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 10:48:58     http://localhost:8080/mypetstore/viewCategory?categoryId=BIRDS 跳转到商品种类 BIRDS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 10:48:59     http://localhost:8080/mypetstore/viewProduct?productId=AV-SB-02 查看产品 Finch';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 11:43:25     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 11:43:27     http://localhost:8080/mypetstore/viewCategory?categoryId=FISH 跳转到商品种类 FISH';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 11:43:28     http://localhost:8080/mypetstore/viewProduct?productId=FI-FW-01 查看产品 Koi';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-24 11:43:44     http://localhost:8080/mypetstore/viewCart?null 查看购物车 org.csu.mypetstore.domain.Cart@1e260c88';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-25 20:18:09     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-25 20:18:17     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = '', loginfo = '2019-10-26 10:57:51     http://localhost:8080/mypetstore/newAccount?null 注册账号，验证码错误';
UPDATE mypetstore.log SET logUserId = null, loginfo = '2019-10-26 10:57:59     http://localhost:8080/mypetstore/newAccount?null 注册账号，验证码错误';
UPDATE mypetstore.log SET logUserId = null, loginfo = '2019-10-26 10:58:01     http://localhost:8080/mypetstore/newAccount?null 注册账号，验证码错误';
UPDATE mypetstore.log SET logUserId = null, loginfo = '2019-10-26 10:58:03     http://localhost:8080/mypetstore/newAccount?null 注册账号，验证码错误';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-26 18:41:45     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'je22', loginfo = '2019-10-26 18:42:11     http://localhost:8080/mypetstore/newAccount?null 注册新账号';
UPDATE mypetstore.log SET logUserId = 'je22', loginfo = '2019-10-26 18:42:54     http://localhost:8080/mypetstore/newAccount?null 注册新账号';
UPDATE mypetstore.log SET logUserId = 'je22', loginfo = '2019-10-26 18:43:31     http://localhost:8080/mypetstore/newAccount?null 注册新账号';
UPDATE mypetstore.log SET logUserId = 'je22', loginfo = '2019-10-26 18:44:30     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'je22', loginfo = '2019-10-26 18:44:35     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 's', loginfo = '2019-10-27 23:53:12     http://localhost:8080/mypetstore/newAccount?null 注册账号，验证码错误';
UPDATE mypetstore.log SET logUserId = 's', loginfo = '2019-10-27 23:53:24     http://localhost:8080/mypetstore/newAccount?null 注册新账号';
UPDATE mypetstore.log SET logUserId = 'aa', loginfo = '2019-10-28 00:45:00     http://localhost:8080/mypetstore/newAccount?null 注册账号，验证码错误';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-29 00:06:09     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-29 00:06:13     http://localhost:8080/mypetstore/viewCart?null 查看购物车 org.csu.mypetstore.domain.Cart@57be5c50';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-29 00:06:17     http://localhost:8080/mypetstore/viewCategory?categoryId=DOGS 跳转到商品种类 DOGS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-29 00:06:19     http://localhost:8080/mypetstore/viewProduct?productId=K9-BD-01 查看产品 Bulldog';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-10-29 00:06:20     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-6 添加物品 (EST-6-null) 到购物车';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:08:01     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:15:59     http://localhost:8080/mypetstore/viewCategory?categoryId=BIRDS 跳转到商品种类 BIRDS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:16:12     http://localhost:8080/mypetstore/viewProduct?productId=AV-CB-01 查看产品 Amazon Parrot';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:16:15     http://localhost:8080/mypetstore/viewCategory?categoryId=BIRDS 跳转到商品种类 BIRDS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:37:36     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:37:40     http://localhost:8080/mypetstore/signOff?null 退出账号';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:49:16     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:49:19     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:07     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:09     http://localhost:8080/mypetstore/viewListOrder?username=j2ee 查看订单 []';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:12     http://localhost:8080/mypetstore/signOff?null 退出账号';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:27     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:29     http://localhost:8080/mypetstore/viewCategory?categoryId=BIRDS 跳转到商品种类 BIRDS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:30     http://localhost:8080/mypetstore/viewProduct?productId=AV-CB-01 查看产品 Amazon Parrot';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:32     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-18 (EST-18-null)数量+1 ';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:37     http://localhost:8080/mypetstore/viewItem?itemId=EST-18 查看具体商品 (EST-18-null)';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:39     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-18 (EST-18-null)数量+1 ';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:42     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:44     http://localhost:8080/mypetstore/viewListOrder?username=j2ee 查看订单 []';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:52     http://localhost:8080/mypetstore/viewCategory?categoryId=DOGS 跳转到商品种类 DOGS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:53     http://localhost:8080/mypetstore/viewCategory?categoryId=REPTILES 跳转到商品种类 REPTILES';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:56     http://localhost:8080/mypetstore/viewCategory?categoryId=CATS 跳转到商品种类 CATS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-27 23:59:57     http://localhost:8080/mypetstore/viewCategory?categoryId=BIRDS 跳转到商品种类 BIRDS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:00:42     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:00:47     http://localhost:8080/mypetstore/viewCategory?categoryId=BIRDS 跳转到商品种类 BIRDS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:00:49     http://localhost:8080/mypetstore/viewProduct?productId=AV-SB-02 查看产品 Finch';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:00:50     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-19 添加物品 (EST-19-null) 到购物车';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:00:55     http://localhost:8080/mypetstore/newOrderForm?itemId= 跳转到新订单页面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:00:58     http://localhost:8080/mypetstore/conFirmOrderForm?null 确认生成订单 ';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:01:01     http://localhost:8080/mypetstore/viewOrder?null 查看订单 org.csu.mypetstore.domain.Order@25d3cb23';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:01:06     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:01:07     http://localhost:8080/mypetstore/viewListOrder?username=j2ee 查看订单 [org.csu.mypetstore.domain.Order@2d4ba0c1]';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:08:02     http://localhost:8080/mypetstore/viewCategory?categoryId=DOGS 跳转到商品种类 DOGS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:08:03     http://localhost:8080/mypetstore/viewProduct?productId=K9-CW-01 查看产品 Chihuahua';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:08:04     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-26 添加物品 (EST-26-null) 到购物车';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:25:39     http://localhost:8080/mypetstore/viewCart?null 查看购物车 org.csu.mypetstore.domain.Cart@193b13d3';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:25:40     http://localhost:8080/mypetstore/newOrderForm?itemId= 跳转到新订单页面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:33:03     http://localhost:8080/mypetstore/signOff?null 退出账号';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:39:33     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:39:34     http://localhost:8080/mypetstore/viewCategory?categoryId=BIRDS 跳转到商品种类 BIRDS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:39:35     http://localhost:8080/mypetstore/viewProduct?productId=AV-CB-01 查看产品 Amazon Parrot';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:39:36     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-18 添加物品 (EST-18-null) 到购物车';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 00:43:09     http://localhost:8080/mypetstore/main?null 跳转到主界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 01:03:12     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 01:03:15     http://localhost:8080/mypetstore/signOff?null 退出账号';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:33     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:36     http://localhost:8080/mypetstore/viewCategory?categoryId=FISH 跳转到商品种类 FISH';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:37     http://localhost:8080/mypetstore/viewProduct?productId=FI-SW-01 查看产品 Angelfish';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:39     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-1 添加物品 (EST-1-null) 到购物车';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:40     http://localhost:8080/mypetstore/viewCart?null 查看购物车 org.csu.mypetstore.domain.Cart@6b2bb7f1';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:41     http://localhost:8080/mypetstore/newOrderForm?itemId= 跳转到新订单页面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:44     http://localhost:8080/mypetstore/conFirmOrderForm?null 确认生成订单 ';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:46     http://localhost:8080/mypetstore/viewOrder?null 查看订单 org.csu.mypetstore.domain.Order@1d9c7759';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:52     http://localhost:8080/mypetstore/viewCart?null 查看购物车 org.csu.mypetstore.domain.Cart@4de90563';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:22:55     http://localhost:8080/mypetstore/viewCategory?categoryId=DOGS 跳转到商品种类 DOGS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:23:03     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:23:04     http://localhost:8080/mypetstore/viewListOrder?username=j2ee 查看订单 [org.csu.mypetstore.domain.Order@2aeb5700, org.csu.mypetstore.domain.Order@425bf302]';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2019-11-28 10:23:06     http://localhost:8080/mypetstore/signOff?null 退出账号';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-05 17:17:13     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-05 17:17:18     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-05 17:17:22     http://localhost:8080/mypetstore/viewListOrder?username=j2ee 查看订单 [org.csu.mypetstore.domain.Order@1b7f848f, org.csu.mypetstore.domain.Order@742088b4]';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-05 17:17:37     http://localhost:8080/mypetstore/viewCategory?categoryId=REPTILES 跳转到商品种类 REPTILES';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-05 17:17:38     http://localhost:8080/mypetstore/main?null 跳转到主界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:26:18     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:26:23     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:26:26     http://localhost:8080/mypetstore/viewListOrder?username=j2ee 查看订单 [org.csu.mypetstore.domain.Order@2df845cf, org.csu.mypetstore.domain.Order@31250896]';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:26:33     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:26:36     http://localhost:8080/mypetstore/signOff?null 退出账号';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:26:53     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:26:54     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:26:59     http://localhost:8080/mypetstore/viewListOrder?username=j2ee 查看订单 [org.csu.mypetstore.domain.Order@10f156ef, org.csu.mypetstore.domain.Order@3bd1e1fb]';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:27:04     http://localhost:8080/mypetstore/signOff?null 退出账号';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:27:18     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:27:22     http://localhost:8080/mypetstore/viewCart?null 查看购物车 org.csu.mypetstore.domain.Cart@1ebc1412';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:27:23     http://localhost:8080/mypetstore/newOrderForm?itemId= 跳转到新订单页面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:31:32     http://localhost:8080/mypetstore/conFirmOrderForm?null 确认生成订单 ';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:31:55     http://localhost:8080/mypetstore/viewOrder?null 查看订单 org.csu.mypetstore.domain.Order@7cd1e42c';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:32:01     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:32:04     http://localhost:8080/mypetstore/viewListOrder?username=j2ee 查看订单 [org.csu.mypetstore.domain.Order@b8c7a76, org.csu.mypetstore.domain.Order@3651aac, org.csu.mypetstore.domain.Order@65be0ee8]';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:32:06     http://localhost:8080/mypetstore/viewOrder?orderId=1002 查看订单 org.csu.mypetstore.domain.Order@7cd1e42c';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-07 14:32:27     http://localhost:8080/mypetstore/viewItem?itemId=EST-18 查看具体商品 (EST-18-null)';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:25:20     http://localhost:8080/mypetstore/signOn?null 用户登录';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:25:23     http://localhost:8080/mypetstore/viewCategory?categoryId=BIRDS 跳转到商品种类 BIRDS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:25:24     http://localhost:8080/mypetstore/viewProduct?productId=AV-CB-01 查看产品 Amazon Parrot';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:25:25     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-18 添加物品 (EST-18-null) 到购物车';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:25:28     http://localhost:8080/mypetstore/newOrderForm?itemId= 跳转到新订单页面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:25:43     http://localhost:8080/mypetstore/conFirmOrderForm?null 确认生成订单 ';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:26:14     http://localhost:8080/mypetstore/viewOrder?null 查看订单 org.csu.mypetstore.domain.Order@14df6aa8';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:26:25     http://localhost:8080/mypetstore/viewCart?null 查看购物车 org.csu.mypetstore.domain.Cart@5ac1a926';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:26:27     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:26:36     http://localhost:8080/mypetstore/viewOrder?orderId=1002 查看订单 org.csu.mypetstore.domain.Order@14df6aa8';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:26:41     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:26:45     http://localhost:8080/mypetstore/viewOrder?orderId=1000 查看订单 org.csu.mypetstore.domain.Order@14df6aa8';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:26:53     http://localhost:8080/mypetstore/editAccount?null 跳转到编辑账号信息界面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:26:56     http://localhost:8080/mypetstore/viewOrder?orderId=1001 查看订单 org.csu.mypetstore.domain.Order@14df6aa8';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:43:27     http://localhost:8080/mypetstore/viewCategory?categoryId=DOGS 跳转到商品种类 DOGS';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:43:28     http://localhost:8080/mypetstore/viewProduct?productId=K9-DL-01 查看产品 Dalmation';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:43:30     http://localhost:8080/mypetstore/addItemToCart?workingItemId=EST-10 添加物品 (EST-10-null) 到购物车';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:43:31     http://localhost:8080/mypetstore/newOrderForm?itemId= 跳转到新订单页面';
UPDATE mypetstore.log SET logUserId = 'j2ee', loginfo = '2020-04-10 17:43:34     http://localhost:8080/mypetstore/conFirmOrderForm?null 确认生成订单 ';
UPDATE mypetstore.orders SET userid = 'j2ee', orderdate = '2020-04-10', shipaddr1 = '901 San Antonio Road', shipaddr2 = 'MS UCUP02-206', shipcity = 'Palo Alto', shipstate = 'CA', shipzip = '94303', shipcountry = 'USA', billaddr1 = '901 San Antonio Road', billaddr2 = 'MS UCUP02-206', billcity = 'Palo Alto', billstate = 'CA', billzip = '94303', billcountry = 'USA', courier = 'UPS', totalprice = 18.50, billtofirstname = 'ABC', billtolastname = 'XYX', shiptofirstname = 'ABC', shiptolastname = 'XYX', creditcard = 'ss', exprdate = '2020-04-01', cardtype = 'Visa', locale = 'CA' WHERE orderid = 10000;
UPDATE mypetstore.orders SET userid = 'j2ee', orderdate = '2020-04-10', shipaddr1 = '901 San Antonio Road', shipaddr2 = 'MS UCUP02-206', shipcity = 'Palo Alto', shipstate = 'CA', shipzip = '94303', shipcountry = 'USA', billaddr1 = '901 San Antonio Road', billaddr2 = 'MS UCUP02-206', billcity = 'Palo Alto', billstate = 'CA', billzip = '94303', billcountry = 'USA', courier = 'UPS', totalprice = 193.50, billtofirstname = 'ABC', billtolastname = 'XYX', shiptofirstname = 'ABC', shiptolastname = 'XYX', creditcard = '99999999', exprdate = '2020-04-01', cardtype = 'Visa', locale = 'CA' WHERE orderid = 10001;
UPDATE mypetstore.orderstatus SET timestamp = '2020-04-10', status = 'P' WHERE orderid = 10000 AND linenum = 0;
UPDATE mypetstore.orderstatus SET timestamp = '2020-04-10', status = 'P' WHERE orderid = 10001 AND linenum = 0;
UPDATE mypetstore.product SET category = 'BIRDS', name = 'Amazon Parrot', descn = '<image src="images/bird2.gif">Great companion for up to 75 years' WHERE productid = 'AV-CB-01';
UPDATE mypetstore.product SET category = 'BIRDS', name = 'Finch', descn = '<image src="images/bird1.gif">Great stress reliever' WHERE productid = 'AV-SB-02';
UPDATE mypetstore.product SET category = 'FISH', name = 'Koi', descn = '<image src="images/fish3.gif">Fresh Water fish from Japan' WHERE productid = 'FI-FW-01';
UPDATE mypetstore.product SET category = 'FISH', name = 'Goldfish', descn = '<image src="images/fish2.gif">Fresh Water fish from China' WHERE productid = 'FI-FW-02';
UPDATE mypetstore.product SET category = 'FISH', name = 'Angelfish', descn = '<image src="images/fish1.gif">Salt Water fish from Australia' WHERE productid = 'FI-SW-01';
UPDATE mypetstore.product SET category = 'FISH', name = 'Tiger Shark', descn = '<image src="images/fish4.gif">Salt Water fish from Australia' WHERE productid = 'FI-SW-02';
UPDATE mypetstore.product SET category = 'CATS', name = 'Persian', descn = '<image src="images/cat1.gif">Friendly house cat, doubles as a princess' WHERE productid = 'FL-DLH-02';
UPDATE mypetstore.product SET category = 'CATS', name = 'Manx', descn = '<image src="images/cat2.gif">Great for reducing mouse populations' WHERE productid = 'FL-DSH-01';
UPDATE mypetstore.product SET category = 'DOGS', name = 'Bulldog', descn = '<image src="images/dog2.gif">Friendly dog from England' WHERE productid = 'K9-BD-01';
UPDATE mypetstore.product SET category = 'DOGS', name = 'Chihuahua', descn = '<image src="images/dog4.gif">Great companion dog' WHERE productid = 'K9-CW-01';
UPDATE mypetstore.product SET category = 'DOGS', name = 'Dalmation', descn = '<image src="images/dog5.gif">Great dog for a Fire Station' WHERE productid = 'K9-DL-01';
UPDATE mypetstore.product SET category = 'DOGS', name = 'Poodle', descn = '<image src="images/dog6.gif">Cute dog from France' WHERE productid = 'K9-PO-02';
UPDATE mypetstore.product SET category = 'DOGS', name = 'Golden Retriever', descn = '<image src="images/dog1.gif">Great family dog' WHERE productid = 'K9-RT-01';
UPDATE mypetstore.product SET category = 'DOGS', name = 'Labrador Retriever', descn = '<image src="images/dog5.gif">Great hunting dog' WHERE productid = 'K9-RT-02';
UPDATE mypetstore.product SET category = 'REPTILES', name = 'Iguana', descn = '<image src="images/lizard1.gif">Friendly green friend' WHERE productid = 'RP-LI-02';
UPDATE mypetstore.product SET category = 'REPTILES', name = 'Rattlesnake', descn = '<image src="images/lizard1.gif">Doubles as a watch dog' WHERE productid = 'RP-SN-01';
UPDATE mypetstore.profile SET langpref = 'ENGLISH', favcategory = 'FISH', mylistopt = null, banneropt = null WHERE userid = '2';
UPDATE mypetstore.profile SET langpref = 'ENGLISH', favcategory = 'DOGS', mylistopt = null, banneropt = null WHERE userid = 'a';
UPDATE mypetstore.profile SET langpref = 'english', favcategory = 'CATS', mylistopt = 1, banneropt = 1 WHERE userid = 'ACID';
UPDATE mypetstore.profile SET langpref = null, favcategory = null, mylistopt = null, banneropt = null WHERE userid = 'dddolo';
UPDATE mypetstore.profile SET langpref = 'ENGLISH', favcategory = 'FISH', mylistopt = null, banneropt = null WHERE userid = 'dd_dolo@163.com';
UPDATE mypetstore.profile SET langpref = 'english', favcategory = 'FISH', mylistopt = 1, banneropt = 1 WHERE userid = 'j2ee';
UPDATE mypetstore.profile SET langpref = 'english', favcategory = 'DOGS', mylistopt = null, banneropt = null WHERE userid = 'je22';
UPDATE mypetstore.profile SET langpref = 'ENGLISH', favcategory = 'FISH', mylistopt = null, banneropt = null WHERE userid = 'q';
UPDATE mypetstore.profile SET langpref = 'ENGLISH', favcategory = 'FISH', mylistopt = null, banneropt = null WHERE userid = 're';
UPDATE mypetstore.profile SET langpref = 'english', favcategory = 'DOGS', mylistopt = null, banneropt = null WHERE userid = 's';
UPDATE mypetstore.profile SET langpref = null, favcategory = null, mylistopt = null, banneropt = null WHERE userid = 'try03';
UPDATE mypetstore.profile SET langpref = null, favcategory = null, mylistopt = null, banneropt = null WHERE userid = 'try04';
UPDATE mypetstore.profile SET langpref = null, favcategory = null, mylistopt = null, banneropt = null WHERE userid = 'try05';
UPDATE mypetstore.profile SET langpref = null, favcategory = null, mylistopt = null, banneropt = null WHERE userid = 'try06';
UPDATE mypetstore.profile SET langpref = null, favcategory = null, mylistopt = null, banneropt = null WHERE userid = 'try07';
UPDATE mypetstore.profile SET langpref = null, favcategory = null, mylistopt = null, banneropt = null WHERE userid = 'try08';
UPDATE mypetstore.profile SET langpref = null, favcategory = null, mylistopt = null, banneropt = null WHERE userid = 'try09';
UPDATE mypetstore.sequence SET nextid = 1000 WHERE name = 'linenum';
UPDATE mypetstore.sequence SET nextid = 1008 WHERE name = 'ordernum';
UPDATE mypetstore.signon SET password = '1' WHERE username = '1';
UPDATE mypetstore.signon SET password = '2' WHERE username = '2';
UPDATE mypetstore.signon SET password = 's' WHERE username = 'a';
UPDATE mypetstore.signon SET password = 'ACID' WHERE username = 'ACID';
UPDATE mypetstore.signon SET password = 'b' WHERE username = 'b';
UPDATE mypetstore.signon SET password = 'd' WHERE username = 'd';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'dddolo';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'dd_dolo@163.com';
UPDATE mypetstore.signon SET password = 'j2ee' WHERE username = 'j2ee';
UPDATE mypetstore.signon SET password = '123' WHERE username = 'je22';
UPDATE mypetstore.signon SET password = 'k' WHERE username = 'k';
UPDATE mypetstore.signon SET password = 'q' WHERE username = 'q';
UPDATE mypetstore.signon SET password = 're' WHERE username = 're';
UPDATE mypetstore.signon SET password = 'a' WHERE username = 's';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'try03';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'try04';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'try05';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'try06';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'try07';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'try08';
UPDATE mypetstore.signon SET password = '202cb962ac59075b964b07152d234b70' WHERE username = 'try09';
UPDATE mypetstore.supplier SET name = 'XYZ Pets', status = 'AC', addr1 = '600 Avon Way', addr2 = '', city = 'Los Angeles', state = 'CA', zip = '94024', phone = '212-947-0797' WHERE suppid = 1;
UPDATE mypetstore.supplier SET name = 'ABC Pets', status = 'AC', addr1 = '700 Abalone Way', addr2 = '', city = 'San Francisco ', state = 'CA', zip = '94024', phone = '415-947-0797' WHERE suppid = 2;